# Generated by Django 5.2.4 on 2025-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 1), ('inactive', 2)], default='active', max_length=10),
        ),
    ]
